---
title: "Predicao de preços de Carros"
author: "A equipe"
date: "5 de dezembro de 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(here)
library(caret)
library(elasticnet)
library(RSNNS)

theme_set(theme_minimal())
```


```{r, warning=FALSE, message=FALSE}
treino <- read.csv(here("data/treino.csv"), encoding = "latin1")
validacao <- read.csv(here("data/validacao.csv"), encoding = "latin1")
```


```{r}
treino %>% 
  names()
```

```{r}
treino %>% 
  head()
```

```{r}
set.seed(379)

amostra <- treino[sample(nrow(treino), 5000), ]
```



```{r}
amostra$Year <- as.factor((amostra$Year))
amostra$City <- as.factor(amostra$City)
amostra$State <- as.factor(amostra$State)
amostra$Model <- as.factor(amostra$Model)
amostra$Make <- as.factor(amostra$Make)
```


```{r}
controle <- trainControl(method = "repeatedcv",
                   number = 5,
                   repeats = 10,
                   verboseIter = TRUE)
```

```{r}
preProcessamento <- c("scale", "center", "nzv")
```

```{r}
# modelo.ridge <- train(Price ~ .,
#                       data = amostra,
#                       trControl = controle,
#                       preProcess = preProcessamento,
#                       method = "ridge")
# saveRDS(modelo.ridge, "ridge.rds")
```

```{r}
modelo.ridge <- readRDS(file="ridge.rds")
modelo.ridge
```

```{r}
plot(modelo.ridge, xlab = "Lambda")
```

```{r}
plot(varImp(modelo.ridge))
```

```{r}
set.seed(379)
amostra.validacao <- validacao[sample(nrow(validacao), 5000),]

predicoes <- predict(modelo.ridge)
predicoes

df.ridge.pred <- data.frame(previsao = predicoes, observado = amostra.validacao$Price)

df.ridge.pred %>% 
  ggplot(aes(x = previsao,
             y = observado - previsao,
             colour = observado - previsao)) +
  geom_jitter()
```

```{r}
modelo.ridge$results %>% 
  filter(RMSE == min(RMSE)) %>% 
  select(RMSE,
         Rsquared)
```

```{r}
# modelo.knn <- train(Price ~.,
#                     data = amostra,
#                     trControl = controle,
#                     preProcess = preProcessamento,
#                     method = "knn")
# saveRDS(modelo.knn, "knn.rds")
```

```{r}
modelo.knn <- readRDS(file="knn.rds")
modelo.knn
```

```{r}
plot(modelo.knn, xlab = "#Vizinhos (k)")
```

```{r}
plot(varImp(modelo.knn))
```

```{r}
predicoes.knn <- predict(modelo.knn)
predicoes.knn

df.knn.pred <- data.frame(previsao = predicoes.knn, observado = amostra.validacao$Price)

df.knn.pred %>% 
  ggplot(aes(x = previsao,
             y = observado - previsao,
             colour = observado - previsao)) +
  geom_jitter()
```


```{r}
modelo.knn$results %>% 
  filter(RMSE == min(RMSE)) %>% 
  select(RMSE,
         Rsquared)
```


```{r}
removeNaoAlfanumericos <- function(x) str_replace_all(x, "[^[:alnum:]]", "")
```

```{r}
amostra$City <- removeNaoAlfanumericos(amostra$City)
amostra$State <- removeNaoAlfanumericos(amostra$State)
amostra$Model <- removeNaoAlfanumericos(amostra$Model)
amostra$Make <- removeNaoAlfanumericos(amostra$Make)
```

```{r}
# modelo.mlp <- caret::train(Price ~ .,
#                     data = amostra,
#                     trControl = controle,
#                     preProcess = preProcessamento,
#                     method = "mlp")
# saveRDS(modelo.mlp, "mlp.rds")
```

```{r}
modelo.mlp <- readRDS(file="mlp.rds")
modelo.mlp
```

```{r}
plot(modelo.mlp)
```

```{r}
predicoes.mlp <- predict(modelo.mlp)
predicoes.mlp

df.mlp.pred <- data.frame(previsao = predicoes.mlp, observado = amostra.validacao$Price)

df.mlp.pred %>% 
  ggplot(aes(x = previsao,
             y = observado - previsao,
             colour = observado - previsao)) +
  geom_jitter()
```

```{r}
modelo.mlp$results %>% 
  filter(RMSE == min(RMSE)) %>% 
  select(RMSE,
         Rsquared)
```